
tasks:
  - name: terminal1
    init: |
      

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
gitConfig:
  alias.history: "log --pretty=oneline"

vscode:
  extensions:
    - ritwickdey.LiveServer
    - esbenp.prettier-vscode
    - eamodio.gitlens
    
